/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import model.Vaga;

/**
 *
 * @author ranoc
 */
public class AddVagaDialog extends javax.swing.JDialog {
    private int idNovaVaga;
    private static Vaga vaga;

    /**
     * Creates new form AddVagaDialog
     */
    public AddVagaDialog(java.awt.Frame parent, int id) {
        super(parent, "Adicionar Vaga", true);
        idNovaVaga = id;
        initComponents();
    }

    public Vaga getVaga() {
        return vaga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        inputDuracao = new javax.swing.JTextField();
        labelDuracao = new javax.swing.JLabel();
        inputCidade1 = new javax.swing.JTextField();
        labelCidade1 = new javax.swing.JLabel();
        inputCargaHoraria = new javax.swing.JTextField();
        labelCargaHoraria = new javax.swing.JLabel();
        inputEstado1 = new javax.swing.JTextField();
        labelEstado1 = new javax.swing.JLabel();
        labelDesc1 = new javax.swing.JLabel();
        inputSalario = new javax.swing.JTextField();
        labelSal = new javax.swing.JLabel();
        labelNome1 = new javax.swing.JLabel();
        inputNome1 = new javax.swing.JTextField();
        labelModeloTrab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputDescricao1 = new javax.swing.JTextArea();
        labelAreaAtuacao = new javax.swing.JLabel();
        inputAreaAtuacao = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        inputFiltroCidade = new javax.swing.JTextField();
        labelCidade2 = new javax.swing.JLabel();
        inputFiltroUni = new javax.swing.JTextField();
        labelAreaAtuacao1 = new javax.swing.JLabel();
        inputFiltroEstado = new javax.swing.JTextField();
        labelSal1 = new javax.swing.JLabel();
        comboModeloTrab = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Vaga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        labelDuracao.setText("Duração em Dias");

        labelCidade1.setText("Cidade");

        labelCargaHoraria.setText("Quantidade de Horas por Semana");

        labelEstado1.setText("Estado");

        labelDesc1.setText("Descrição");

        labelSal.setText("Salário");

        labelNome1.setText("Nome");

        labelModeloTrab.setText("Modelo de Trabalho");

        inputDescricao1.setColumns(20);
        inputDescricao1.setRows(5);
        jScrollPane2.setViewportView(inputDescricao1);

        labelAreaAtuacao.setText("Área de Atuação");

        btnAdd1.setText("OK");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros (opcional)"));

        labelCidade2.setText("Somente da Cidade:");

        labelAreaAtuacao1.setText("Somente na universisdade:");

        labelSal1.setText("Somente do estado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFiltroCidade)
                    .addComponent(labelCidade2)
                    .addComponent(labelAreaAtuacao1)
                    .addComponent(inputFiltroUni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFiltroEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSal1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAreaAtuacao1)
                            .addComponent(labelSal1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFiltroUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCidade2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputFiltroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        comboModeloTrab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "remoto", "presencial" }));
        comboModeloTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloTrabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(inputNome1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCidade1)
                            .addComponent(inputCargaHoraria)
                            .addComponent(comboModeloTrab, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCargaHoraria)
                                    .addComponent(labelCidade1)
                                    .addComponent(labelModeloTrab))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelEstado1)
                                .addComponent(inputEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDuracao)
                                .addComponent(inputDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd1))
                    .addComponent(inputAreaAtuacao)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome1)
                            .addComponent(labelDesc1)
                            .addComponent(labelAreaAtuacao))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelSal)
                                    .addComponent(labelModeloTrab))
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboModeloTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCidade1)
                            .addComponent(labelEstado1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(labelCargaHoraria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAreaAtuacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDesc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(btnAdd1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        try {
            var nome = inputNome1.getText();
            var areaAtuacao = inputAreaAtuacao.getText();
            var cidade = inputCidade1.getText();
            var estado = inputEstado1.getText();
            var salario = Float.parseFloat(inputSalario.getText());
            var cargaHoraria = Integer.parseInt(inputCargaHoraria.getText());
            var duracao = Integer.parseInt(inputDuracao.getText());
            var modeloTrabalho = (String) comboModeloTrab.getSelectedItem();
            var descricao = inputDescricao1.getText();

            vaga = new Vaga(idNovaVaga,
                    nome,
                    areaAtuacao,
                    cidade,
                    estado,
                    modeloTrabalho,
                    salario,
                    cargaHoraria,
                    duracao,
                    descricao,
                    "disponivel",
                    null);
            var filtroCidade = inputFiltroCidade.getText();
            if (!filtroCidade.isBlank()) {
                vaga.setFiltroPorCidade(filtroCidade);
            }
            var filtroEstado = inputFiltroEstado.getText();
            if (!filtroEstado.isBlank()) {
                vaga.setFiltroPorEstado(filtroEstado);
            }
            var filtroUni = inputFiltroUni.getText();
            if (!filtroUni.isBlank()) {
                vaga.setFiltroPorUniversidade(filtroUni);
            }

            /*
            inputNome1.setText("");
            inputAreaAtuacao.setText("");
            inputCidade1.setText("");
            inputEstado1.setText("");
            inputSalario.setText("");
            inputCargaHoraria.setText("");
            inputDuracao.setText("");
            inputModeloTrabalho.setText("");
            inputDescricao1.setText("");
             */
            dispose();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void comboModeloTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloTrabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModeloTrabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JComboBox<String> comboModeloTrab;
    private javax.swing.JTextField inputAreaAtuacao;
    private javax.swing.JTextField inputCargaHoraria;
    private javax.swing.JTextField inputCidade1;
    private javax.swing.JTextArea inputDescricao1;
    private javax.swing.JTextField inputDuracao;
    private javax.swing.JTextField inputEstado1;
    private javax.swing.JTextField inputFiltroCidade;
    private javax.swing.JTextField inputFiltroEstado;
    private javax.swing.JTextField inputFiltroUni;
    private javax.swing.JTextField inputNome1;
    private javax.swing.JTextField inputSalario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAreaAtuacao;
    private javax.swing.JLabel labelAreaAtuacao1;
    private javax.swing.JLabel labelCargaHoraria;
    private javax.swing.JLabel labelCidade1;
    private javax.swing.JLabel labelCidade2;
    private javax.swing.JLabel labelDesc1;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelEstado1;
    private javax.swing.JLabel labelModeloTrab;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelSal;
    private javax.swing.JLabel labelSal1;
    // End of variables declaration//GEN-END:variables
}
