/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SistemaEstagioController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Vaga;
import model.VagasComboBoxModel;

/**
 *
 * @author ranoc
 */
public class AlunoView extends javax.swing.JFrame {

    private Aluno currentAluno;
    private ArrayList<Vaga> vagas = new ArrayList<>();
    private VagasComboBoxModel vagasComboModel;
    SistemaEstagioController system;

    /**
     * Creates new form AlunoView
     */
    public AlunoView() throws IOException, Exception {
        this.system = new SistemaEstagioController();
        if (!system.recuperaSistema()) {
            var newAlunoFrame = new AddAlunoDialog(this);
            newAlunoFrame.setVisible(true);
            var aluno = newAlunoFrame.getAluno();
            if (aluno == null) {
                return;
            }
            system.cadastraPrimeiroAluno(aluno);
        }

        currentAluno = system.getCurrentAluno();
        if (currentAluno == null) {
            var newAlunoFrame = new AddAlunoDialog(this);
            newAlunoFrame.setVisible(true);
            var aluno = newAlunoFrame.getAluno();
            if (aluno == null) {
                return;
            }
            system.addAluno(aluno);
            currentAluno = aluno;
        }
        vagasComboModel = new VagasComboBoxModel(system.getVagasFiltradas(currentAluno));

        vagas = system.getVagasFiltradas(currentAluno);
        initComponents();
        populateVagas();

        comboVaga.setVisible(false);
        labelVaga.setVisible(false);
        btnCandidatarAluno.setVisible(false);
    }

    private void populateVagas() {
        var showVagas = "";
        for (var vaga : vagas) {
            showVagas += vaga.textFieldPrep();
        }
        tareaVagas.setText(showVagas);
    }
    
    public void update() {
        populateVagas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaVagas = new javax.swing.JTextArea();
        comboVaga = new javax.swing.JComboBox(vagasComboModel);
        btnCandidatarAluno = new javax.swing.JButton();
        labelVaga = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filtroNome = new javax.swing.JTextField();
        filtroAreaAt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        filtroNomeEmp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filtroModalidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filtroEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        filtroCidade = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAddProjeto = new javax.swing.JMenuItem();
        miEditarAluno = new javax.swing.JMenuItem();
        menuVagasDispo = new javax.swing.JMenuItem();
        menuVagasCandid = new javax.swing.JMenuItem();
        menuCandidatar = new javax.swing.JMenu();
        miCandVaga = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perspectiva do Aluno");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vagas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        tareaVagas.setEditable(false);
        tareaVagas.setColumns(20);
        tareaVagas.setRows(5);
        tareaVagas.setEnabled(false);
        jScrollPane1.setViewportView(tareaVagas);

        comboVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVagaActionPerformed(evt);
            }
        });

        btnCandidatarAluno.setText("OK");
        btnCandidatarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatarAlunoActionPerformed(evt);
            }
        });

        labelVaga.setText("Selecionar Vaga");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar vagas"));

        jLabel1.setText("Nome");

        jLabel2.setText("Área de Atuação");

        jLabel3.setText("Nome da Empresa");

        jLabel4.setText("Cidade");

        jLabel5.setText("Estado");

        jLabel6.setText("Modalidade");

        btnFiltrar.setText("Aplicar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFiltrar)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filtroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filtroAreaAt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filtroNomeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                            .addComponent(filtroModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(filtroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                            .addComponent(filtroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnFiltrar))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filtroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filtroAreaAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filtroNomeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(filtroModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filtroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(filtroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCandidatarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelVaga)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelVaga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCandidatarAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        miAddProjeto.setText("Adicionar Projeto Pessoal");
        miAddProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddProjetoActionPerformed(evt);
            }
        });
        jMenu2.add(miAddProjeto);

        miEditarAluno.setText("Editar Aluno");
        miEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(miEditarAluno);

        menuVagasDispo.setText("Listar Vagas Disponíveis");
        menuVagasDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVagasDispoActionPerformed(evt);
            }
        });
        jMenu2.add(menuVagasDispo);

        menuVagasCandid.setText("Listar Vagas Candidatadas");
        menuVagasCandid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVagasCandidActionPerformed(evt);
            }
        });
        jMenu2.add(menuVagasCandid);

        jMenuBar1.add(jMenu2);

        menuCandidatar.setText("Candidatar");

        miCandVaga.setText("Selecionar Vaga");
        miCandVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCandVagaActionPerformed(evt);
            }
        });
        menuCandidatar.add(miCandVaga);

        jMenuBar1.add(menuCandidatar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            system.save();
        } catch (IOException ex) {
            Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miCandVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCandVagaActionPerformed
        vagasComboModel.clear();
        var vagasDiponiveis = system.getVagasFiltradas(currentAluno);
        if(vagasDiponiveis.isEmpty()){
            JOptionPane.showMessageDialog(this, "Não existem vagas disponíveis!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        vagasComboModel.addListVaga(vagasDiponiveis);
        tareaVagas.setText("");
        comboVaga.setVisible(true);
        labelVaga.setVisible(true);
        btnCandidatarAluno.setVisible(true);
        update();
    }//GEN-LAST:event_miCandVagaActionPerformed

    private void btnCandidatarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatarAlunoActionPerformed
        
        var vagaCadastrada = vagasComboModel.getSelectedItem();
        system.addVagaAluno(currentAluno.getCPF(), vagaCadastrada.getId());

        update();

        comboVaga.setVisible(false);
        labelVaga.setVisible(false);
        btnCandidatarAluno.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCandidatarAlunoActionPerformed

    private void comboVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVagaActionPerformed
        Vaga selectedVaga = (Vaga) comboVaga.getSelectedItem();
        if(selectedVaga == null)
            return;
        tareaVagas.setText(selectedVaga.textFieldPrep());
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVagaActionPerformed

    private void miEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarAlunoActionPerformed
        var editarAlunoFrame = new EditarAlunoDialog(this, currentAluno);
        editarAlunoFrame.setVisible(true);
        var alunoEditado = editarAlunoFrame.getAluno();
        if(alunoEditado != null)
            system.addAluno(alunoEditado);
        update();
        // TODO add your handling code here:
    }//GEN-LAST:event_miEditarAlunoActionPerformed

    private void menuVagasDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVagasDispoActionPerformed
        vagas = system.getVagasFiltradas(currentAluno);
        update();
// TODO add your handling code here:
    }//GEN-LAST:event_menuVagasDispoActionPerformed

    private void menuVagasCandidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVagasCandidActionPerformed
        vagas = system.getVagasPorAluno(currentAluno);
        update();
// TODO add your handling code here:
    }//GEN-LAST:event_menuVagasCandidActionPerformed

    private void miAddProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddProjetoActionPerformed
        var addProjetoDialog = new AddProjDialog(this);
        addProjetoDialog.setVisible(true);
        var projetoPessoal = addProjetoDialog.getProjetoPessoal();
        if(projetoPessoal != null)
            currentAluno.addProjetoPessoal(projetoPessoal);
// TODO add your handling code here:
    }//GEN-LAST:event_miAddProjetoActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        var areaAt = filtroAreaAt.getText();
        var nomeVaga = filtroNome.getText();
        var modalidade = filtroModalidade.getText();
        var nomeEmp = filtroNomeEmp.getText();
        var cidade = filtroCidade.getText();
        var estado = filtroEstado.getText();
        
        var vagasFiltradas = system.getVagasFiltradas(currentAluno);
        
        if(!areaAt.isBlank())
            vagasFiltradas = system.filtraVagasPorArea(vagasFiltradas, areaAt);

         if(!nomeVaga.isBlank())
            vagasFiltradas = system.filtraVagasPorNome(vagasFiltradas, nomeVaga);

         if(!modalidade.isBlank())
            vagasFiltradas = system.filtraVagasPorModalidade(vagasFiltradas, modalidade);

         if(!nomeEmp.isBlank())
            vagasFiltradas = system.filtraVagasPorNomeEmpresa(vagasFiltradas, nomeEmp);

         if(!cidade.isBlank())
            vagasFiltradas = system.filtraVagasPorCidade(vagasFiltradas, cidade);

         if(!estado.isBlank())
            vagasFiltradas = system.filtraVagasPorEstado(vagasFiltradas, estado);

         this.vagas = vagasFiltradas;
         update();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    var alunoView = new AlunoView();
                    alunoView.setVisible(true);
                    alunoView.addWindowListener(new WindowAdapter()  {
                        @Override
                        public void windowClosing (WindowEvent e){
                            try {
                                alunoView.system.save();
                            } catch (IOException ex) {
                                Logger.getLogger(EmpresaView.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });
                } catch (IOException ex) {
                    Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(AlunoView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatarAluno;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> comboVaga;
    private javax.swing.JTextField filtroAreaAt;
    private javax.swing.JTextField filtroCidade;
    private javax.swing.JTextField filtroEstado;
    private javax.swing.JTextField filtroModalidade;
    private javax.swing.JTextField filtroNome;
    private javax.swing.JTextField filtroNomeEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVaga;
    private javax.swing.JMenu menuCandidatar;
    private javax.swing.JMenuItem menuVagasCandid;
    private javax.swing.JMenuItem menuVagasDispo;
    private javax.swing.JMenuItem miAddProjeto;
    private javax.swing.JMenuItem miCandVaga;
    private javax.swing.JMenuItem miEditarAluno;
    private javax.swing.JTextArea tareaVagas;
    // End of variables declaration//GEN-END:variables
}
