/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SistemaEstagioController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Empresa;
import model.Vaga;
import model.VagasComboBoxModel;
import model.AlunoComboBoxModel;
import model.Certificado;

/**
 *
 * @author ranoc
 */
public class EmpresaView extends javax.swing.JFrame {

    private Empresa currentEmpresa;
    private VagasComboBoxModel vagasComboModel;
    private AlunoComboBoxModel alunosComboBoxModel = new AlunoComboBoxModel();
    private String nomeTituloPainelPrincipal = "Vagas Adicionadas";
    SistemaEstagioController system;

    /**
     * Creates new form EmpresaView
     *
     * @throws java.io.IOException
     */
    
    public EmpresaView() throws Exception{
        this.system = new SistemaEstagioController();
        if(!system.recuperaSistema()){
            var newEmpresaFrame = new AddEmpresaDialog(this);
            newEmpresaFrame.setVisible(true);
            var empresa = newEmpresaFrame.getEmpresa();
            if (empresa == null) {
                return;
            }
            system.cadastraPrimeiraEmpresa(empresa);
        }
        currentEmpresa = system.getCurrentEmpresa(); 
        vagasComboModel = new VagasComboBoxModel(system.getVagas());
        initComponents();
        
        //jLabel1.setVisible(false);
        //comboSelectAluno.setVisible(false);
        nomeTituloPainelPrincipal = "vaga";
        populateTextArea(false);        
    }
    
    private void populateTextArea(boolean hasFiltro) {
        var textAreaString = "";
        Vaga selectedVaga = (Vaga) comboVaga.getSelectedItem();
        switch (nomeTituloPainelPrincipal) {
            case "aluno" -> {
                jLabel1.setVisible(false);
                comboSelectAluno.setVisible(false);
                if(hasFiltro){
                    if(selectedVaga == null){
                        JOptionPane.showMessageDialog(this, 
                            "Nenhuma vaga selecionada", 
                            "Erro", 
                            JOptionPane.ERROR_MESSAGE
                        );
                        break;
                    }
                    for (var aluno : system.getVagaById(selectedVaga.getId()).getAlunos()) {
                        textAreaString += aluno.textFieldPrep();
                    }
                    taListItems.setText(textAreaString);
                    break;
                }                
                for (var aluno : system.getTodosAlunosPorEmpresa(currentEmpresa.getCNPJ())) {
                    textAreaString += aluno.textFieldPrep();
                }
                taListItems.setText(textAreaString);
            }
            case "vaga" -> {
                jLabel1.setVisible(false);
                comboSelectAluno.setVisible(false);
                if(hasFiltro){
                    taListItems.setText(selectedVaga.textFieldPrep());
                    break;
                }
                for (var vaga : currentEmpresa.getVagas()) {
                    textAreaString += vaga.textFieldPrep();
                }
                taListItems.setText(textAreaString);
            }
            case "contratar" -> {
                
                if(selectedVaga == null){
                    JOptionPane.showMessageDialog(this, 
                        "Nenhuma vaga selecionada", 
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE
                    );
                    break;
                }
                alunosComboBoxModel.clear();
                var alunos = system.getTodosAlunosPorEmpresa(currentEmpresa.getCNPJ());
                if(alunos.isEmpty()){
                    JOptionPane.showMessageDialog(this, 
                        "Nenhum aluno se candidatou a vaga!", 
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE
                    );
                    break;
                }
                alunosComboBoxModel.addListALuno(alunos);
                jLabel1.setVisible(true);
                comboSelectAluno.setVisible(true);
            }
            default -> {
                break;
            }
        }
    }

    private void updateFrame() {
        populateTextArea(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        panelAddEmpresa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListItems = new javax.swing.JTextArea();
        labelVaga = new javax.swing.JLabel();
        comboVaga = new javax.swing.JComboBox(vagasComboModel);
        comboSelectAluno = new javax.swing.JComboBox(alunosComboBoxModel);
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSaveFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAddVaga = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenu();
        miListarVagas = new javax.swing.JMenuItem();
        miListarAlunos = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        miEditarVaga = new javax.swing.JMenuItem();
        miEditarEmpresa = new javax.swing.JMenuItem();
        menuGeraCertificado = new javax.swing.JMenu();
        miGeraCertificado = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perspectiva da Empresa");

        panelAddEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, nomeTituloPainelPrincipal, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        panelAddEmpresa.setToolTipText("");

        taListItems.setEditable(false);
        taListItems.setColumns(20);
        taListItems.setRows(5);
        taListItems.setEnabled(false);
        jScrollPane1.setViewportView(taListItems);

        labelVaga.setText("Filtrar por vaga");

        comboVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVagaActionPerformed(evt);
            }
        });

        comboSelectAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecionar Aluno");

        javax.swing.GroupLayout panelAddEmpresaLayout = new javax.swing.GroupLayout(panelAddEmpresa);
        panelAddEmpresa.setLayout(panelAddEmpresaLayout);
        panelAddEmpresaLayout.setHorizontalGroup(
            panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                        .addGroup(panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVaga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSelectAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        panelAddEmpresaLayout.setVerticalGroup(
            panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelVaga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelAddEmpresaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSelectAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("File");

        menuItemSaveFile.setText("Save");
        menuItemSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveFileActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSaveFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Adicionar");

        menuAddVaga.setText("Vaga");
        menuAddVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddVagaActionPerformed(evt);
            }
        });
        jMenu2.add(menuAddVaga);

        jMenuBar1.add(jMenu2);

        menuListar.setText("Listar");

        miListarVagas.setText("Vagas");
        miListarVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarVagasActionPerformed(evt);
            }
        });
        menuListar.add(miListarVagas);

        miListarAlunos.setText("Alunos");
        miListarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarAlunosActionPerformed(evt);
            }
        });
        menuListar.add(miListarAlunos);

        jMenuBar1.add(menuListar);

        menuEditar.setText("Editar");

        miEditarVaga.setText("Vaga");
        miEditarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarVagaActionPerformed(evt);
            }
        });
        menuEditar.add(miEditarVaga);

        miEditarEmpresa.setText("Empresa Atual");
        miEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarEmpresaActionPerformed(evt);
            }
        });
        menuEditar.add(miEditarEmpresa);

        jMenuBar1.add(menuEditar);

        menuGeraCertificado.setText("Gerar");

        miGeraCertificado.setText("Certificado");
        miGeraCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGeraCertificadoActionPerformed(evt);
            }
        });
        menuGeraCertificado.add(miGeraCertificado);

        jMenuBar1.add(menuGeraCertificado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAddEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAddEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveFileActionPerformed
        try {
            system.save();
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(EmpresaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemSaveFileActionPerformed

    private void menuAddVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddVagaActionPerformed
        var newVagaFrame = new AddVagaDialog(this, system.getPrimeiroIdDisponivelVaga());
        newVagaFrame.setVisible(true);
        var vaga = newVagaFrame.getVaga();
        if (vaga != null) 
            system.addVaga(currentEmpresa.getCNPJ(), vaga);
        updateFrame();
// TODO add your handling code here:
    }//GEN-LAST:event_menuAddVagaActionPerformed

    private void miListarVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarVagasActionPerformed
        nomeTituloPainelPrincipal = "vaga";
        updateFrame();
        // TODO add your handling code here:
    }//GEN-LAST:event_miListarVagasActionPerformed

    private void miListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarAlunosActionPerformed
        nomeTituloPainelPrincipal = "aluno";
        updateFrame();
        // TODO add your handling code here:
    }//GEN-LAST:event_miListarAlunosActionPerformed

    private void comboVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVagaActionPerformed
        populateTextArea(true);  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVagaActionPerformed

    private void miEditarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarVagaActionPerformed
        var vagaEditFrame = new EditVagaDialog(this, system.getVagas());
        vagaEditFrame.setVisible(true);
        var vagaEditada = vagaEditFrame.getVagaEditada();
        if (vagaEditada == null) {
            return;
        }
        system.editVaga(vagaEditada);
        updateFrame();

    }//GEN-LAST:event_miEditarVagaActionPerformed

    
    
    private void miEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarEmpresaActionPerformed
        var empresaEditFrame = new EditarEmpresaDialog(this, currentEmpresa);
        empresaEditFrame.setVisible(true);
        var empresaEditada = empresaEditFrame.getEmpresa();
        if (empresaEditada == null || empresaEditFrame.equals(currentEmpresa)) {
            return;
        }
        system.editEmpresa(empresaEditada);
        updateFrame();
        // TODO add your handling code here:
    }//GEN-LAST:event_miEditarEmpresaActionPerformed

    private void miGeraCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGeraCertificadoActionPerformed
        var selectDialog = new SelectCertificadoDialog(this, 
                system.getVagasEmpresa(currentEmpresa.getCNPJ()), 
                currentEmpresa);
        selectDialog.setVisible(true);
        var certificado = selectDialog.getCertificado();
        files.FileManagementSystem.geraCertificadoAluno(certificado);
        JOptionPane.showMessageDialog(this, 
            "O certificado etá disponível no arquivo certificado.txt no diretório deste executável :)", 
            "Certificado gerado!", 
            JOptionPane.INFORMATION_MESSAGE
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_miGeraCertificadoActionPerformed

    private void comboSelectAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectAlunoActionPerformed
        Vaga selectedVaga = (Vaga) comboVaga.getSelectedItem();
        Aluno selectedAluno = (Aluno) comboSelectAluno.getSelectedItem();
        if(selectedAluno == null || selectedVaga == null){
            JOptionPane.showMessageDialog(this, 
                "Aluno ou vaga não selecionados!", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE
            );
            
        }
    }//GEN-LAST:event_comboSelectAlunoActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    var empresaView = new EmpresaView();
                    empresaView.setVisible(true);
                    empresaView.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosing(WindowEvent e){
                            try {
                                empresaView.system.save();
                            } catch (IOException ex) {
                                Logger.getLogger(EmpresaView.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });
                } catch (IOException ex) {
                    Logger.getLogger(EmpresaView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(EmpresaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSelectAluno;
    private javax.swing.JComboBox<String> comboVaga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVaga;
    private javax.swing.JMenuItem menuAddVaga;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuGeraCertificado;
    private javax.swing.JMenuItem menuItemSaveFile;
    private javax.swing.JMenu menuListar;
    private javax.swing.JMenuItem miEditarEmpresa;
    private javax.swing.JMenuItem miEditarVaga;
    private javax.swing.JMenuItem miGeraCertificado;
    private javax.swing.JMenuItem miListarAlunos;
    private javax.swing.JMenuItem miListarVagas;
    private javax.swing.JPanel panelAddEmpresa;
    private javax.swing.JTextArea taListItems;
    // End of variables declaration//GEN-END:variables
}
