/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Aluno;
import model.AlunoComboBoxModel;
import model.Certificado;
import model.Empresa;
import model.Vaga;
import model.VagasComboBoxModel;

/**
 *
 * @author ranoc
 */
public class SelectCertificadoDialog extends javax.swing.JDialog {
    private Certificado cert;
    private AlunoComboBoxModel alunosComboBoxModel;
    private VagasComboBoxModel vagasComboModel;
    private Empresa empresa;
    /**
     * Creates new form SelectCertificadoDialog
     */
    public SelectCertificadoDialog(java.awt.Frame parent, ArrayList<Vaga> listVagas, Empresa empresa) {
        super(parent, "Selecione", true);
        this.empresa = empresa;
        vagasComboModel = new VagasComboBoxModel(listVagas);
        initComponents();
    }

    public Certificado getCertificado() {
        return cert;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNomeO = new javax.swing.JLabel();
        inputOrientador = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        comboVaga = new javax.swing.JComboBox(vagasComboModel);
        labelVaga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboSelectAluno = new javax.swing.JComboBox(alunosComboBoxModel);
        labelArea1 = new javax.swing.JLabel();
        inputDtInicio = new javax.swing.JTextField();
        inputDtFim = new javax.swing.JTextField();
        labelArea2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione o Aluno que receberá o certificado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        labelNomeO.setText("Nome do Orientador");

        btnAdd.setText("OK");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        comboVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVagaActionPerformed(evt);
            }
        });

        labelVaga.setText("Vaga");

        jLabel1.setText("Selecionar Aluno");

        comboSelectAluno.setEnabled(false);
        comboSelectAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectAlunoActionPerformed(evt);
            }
        });

        labelArea1.setText("Data de inicio");

        inputDtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDtInicioActionPerformed(evt);
            }
        });

        labelArea2.setText("Data de término");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelVaga)
                            .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboSelectAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNomeO)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputOrientador)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelArea1)
                                    .addComponent(inputDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelArea2)
                                        .addGap(0, 101, Short.MAX_VALUE))
                                    .addComponent(inputDtFim))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVaga)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSelectAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNomeO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelArea1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelArea2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVagaActionPerformed
        Vaga selectedVaga = (Vaga) comboVaga.getSelectedItem();
        if(selectedVaga == null){
            JOptionPane.showMessageDialog(this,
                "Vaga não selecionada!",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        comboSelectAluno.setEnabled(true);
        alunosComboBoxModel.addListALuno(selectedVaga.getAlunos());
// TODO add your handling code here:
    }//GEN-LAST:event_comboVagaActionPerformed

    private void comboSelectAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectAlunoActionPerformed
        
    }//GEN-LAST:event_comboSelectAlunoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Vaga selectedVaga = (Vaga) comboVaga.getSelectedItem();
        if(selectedVaga == null){
            JOptionPane.showMessageDialog(this,
                "Vaga não selecionada!",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        Aluno selectedAluno = (Aluno) comboSelectAluno.getSelectedItem();
        if(selectedAluno == null){
            JOptionPane.showMessageDialog(this,
                "Aluno não selecionado!",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        var dataInicio = inputDtInicio.getText();
        var dataFim = inputDtFim.getText();
        var orientador = inputOrientador.getText();
        
        cert = new Certificado(selectedAluno, selectedVaga, empresa, dataInicio, dataFim, orientador);
        
        inputOrientador.setText("");
        inputDtFim.setText("");
        inputDtInicio.setText("");
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void inputDtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDtInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> comboSelectAluno;
    private javax.swing.JComboBox<String> comboVaga;
    private javax.swing.JTextField inputDtFim;
    private javax.swing.JTextField inputDtInicio;
    private javax.swing.JTextField inputOrientador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelArea1;
    private javax.swing.JLabel labelArea2;
    private javax.swing.JLabel labelNomeO;
    private javax.swing.JLabel labelVaga;
    // End of variables declaration//GEN-END:variables
}
